### PR TITLE
Added Release GitHub workflow

### LINKED ISSUE #42: Add Release GitHub workflow
Add a GitHub action workflow to automate creating a GitHub release.

### PR DESCRIPTION
**Pull request by gabb222**
Fixes #42 

Not tested, but taken from a widely used Theia repository

### CODE REVIEW

**Comment by gabb222** [comment]
@Theia-Scientific/developers help needed, not sure why the checks failed

**Review by volks73 — APPROVED** [review]
Looks good.

**Comment by volks73** [comment]
@gabb222 Checks failed because the order of keys for a dictionary are not guaranteed from execution to execution. The tests need to be re-written to use `in` instead of `==`:

```python
assert 'tests/assets/example_file_1.ts.png' in list(test_data.keys())
assert 'tests/assets/example_file_2.ts.png' in list(test_data.keys())
```

This will ensure the keys exist and are in the list but not worry about order. The other option is to sort the list (since you have a sane naming convention):

```python
assert sort(list(test_data.keys()))==['tests/assets/example_file_1.ts.png','tests/assets/example_file_2.ts.png']
```

**Comment by gabb222** [comment]
Made proper syntax changes within the unit tests to have the checks pass

**Pull request merged**
